package com.app.entity;

import java.util.Date;

public class TRemoteinfomanage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.INFO_ID
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.JBXX
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String jbxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.NUM
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.STATION_NAME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.STATION_ID
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNIT
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String dispatchUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNITID
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String dispatchUnitid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.ZFBXH
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String zfbxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.IS_ZX
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String isZx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.BZ_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String bzMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.BZ_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private Date bzTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.BZR_PHONE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String bzrPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.RWMS
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String rwms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.XC_OPINION
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String xcOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.JY_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String jyMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.JY_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private Date jyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.SH_OPINION
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String shOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.SH_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String shMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.SH_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private Date shTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.PZ_OPINION
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String pzOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.PZ_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String pzMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.PZ_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private Date pzTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.XCZXJG
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String xczxjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.ZX_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String zxMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.ZX_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private Date zxTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.FJ
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String fj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.IS_JJD
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String isJjd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.IS_PUT
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String isPut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTECT.T_REMOTEINFOMANAGE.IS_ALLEDIT
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    private String isAlledit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.INFO_ID
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.INFO_ID
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.INFO_ID
     *
     * @param infoId the value for PROTECT.T_REMOTEINFOMANAGE.INFO_ID
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setInfoId(String infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.JBXX
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.JBXX
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getJbxx() {
        return jbxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.JBXX
     *
     * @param jbxx the value for PROTECT.T_REMOTEINFOMANAGE.JBXX
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setJbxx(String jbxx) {
        this.jbxx = jbxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.NUM
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.NUM
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.NUM
     *
     * @param num the value for PROTECT.T_REMOTEINFOMANAGE.NUM
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.STATION_NAME
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.STATION_NAME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.STATION_NAME
     *
     * @param stationName the value for PROTECT.T_REMOTEINFOMANAGE.STATION_NAME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.STATION_ID
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.STATION_ID
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.STATION_ID
     *
     * @param stationId the value for PROTECT.T_REMOTEINFOMANAGE.STATION_ID
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setStationId(String stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNIT
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNIT
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getDispatchUnit() {
        return dispatchUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNIT
     *
     * @param dispatchUnit the value for PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNIT
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setDispatchUnit(String dispatchUnit) {
        this.dispatchUnit = dispatchUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNITID
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNITID
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getDispatchUnitid() {
        return dispatchUnitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNITID
     *
     * @param dispatchUnitid the value for PROTECT.T_REMOTEINFOMANAGE.DISPATCH_UNITID
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setDispatchUnitid(String dispatchUnitid) {
        this.dispatchUnitid = dispatchUnitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.ZFBXH
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.ZFBXH
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getZfbxh() {
        return zfbxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.ZFBXH
     *
     * @param zfbxh the value for PROTECT.T_REMOTEINFOMANAGE.ZFBXH
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setZfbxh(String zfbxh) {
        this.zfbxh = zfbxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.IS_ZX
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.IS_ZX
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getIsZx() {
        return isZx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.IS_ZX
     *
     * @param isZx the value for PROTECT.T_REMOTEINFOMANAGE.IS_ZX
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setIsZx(String isZx) {
        this.isZx = isZx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.BZ_MAN
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.BZ_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getBzMan() {
        return bzMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.BZ_MAN
     *
     * @param bzMan the value for PROTECT.T_REMOTEINFOMANAGE.BZ_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setBzMan(String bzMan) {
        this.bzMan = bzMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.BZ_TIME
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.BZ_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public Date getBzTime() {
        return bzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.BZ_TIME
     *
     * @param bzTime the value for PROTECT.T_REMOTEINFOMANAGE.BZ_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setBzTime(Date bzTime) {
        this.bzTime = bzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.BZR_PHONE
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.BZR_PHONE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getBzrPhone() {
        return bzrPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.BZR_PHONE
     *
     * @param bzrPhone the value for PROTECT.T_REMOTEINFOMANAGE.BZR_PHONE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setBzrPhone(String bzrPhone) {
        this.bzrPhone = bzrPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.RWMS
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.RWMS
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getRwms() {
        return rwms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.RWMS
     *
     * @param rwms the value for PROTECT.T_REMOTEINFOMANAGE.RWMS
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setRwms(String rwms) {
        this.rwms = rwms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.XC_OPINION
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.XC_OPINION
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getXcOpinion() {
        return xcOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.XC_OPINION
     *
     * @param xcOpinion the value for PROTECT.T_REMOTEINFOMANAGE.XC_OPINION
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setXcOpinion(String xcOpinion) {
        this.xcOpinion = xcOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.JY_MAN
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.JY_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getJyMan() {
        return jyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.JY_MAN
     *
     * @param jyMan the value for PROTECT.T_REMOTEINFOMANAGE.JY_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setJyMan(String jyMan) {
        this.jyMan = jyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.JY_TIME
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.JY_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public Date getJyTime() {
        return jyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.JY_TIME
     *
     * @param jyTime the value for PROTECT.T_REMOTEINFOMANAGE.JY_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setJyTime(Date jyTime) {
        this.jyTime = jyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.SH_OPINION
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.SH_OPINION
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getShOpinion() {
        return shOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.SH_OPINION
     *
     * @param shOpinion the value for PROTECT.T_REMOTEINFOMANAGE.SH_OPINION
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setShOpinion(String shOpinion) {
        this.shOpinion = shOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.SH_MAN
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.SH_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getShMan() {
        return shMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.SH_MAN
     *
     * @param shMan the value for PROTECT.T_REMOTEINFOMANAGE.SH_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setShMan(String shMan) {
        this.shMan = shMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.SH_TIME
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.SH_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public Date getShTime() {
        return shTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.SH_TIME
     *
     * @param shTime the value for PROTECT.T_REMOTEINFOMANAGE.SH_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setShTime(Date shTime) {
        this.shTime = shTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.PZ_OPINION
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.PZ_OPINION
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getPzOpinion() {
        return pzOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.PZ_OPINION
     *
     * @param pzOpinion the value for PROTECT.T_REMOTEINFOMANAGE.PZ_OPINION
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setPzOpinion(String pzOpinion) {
        this.pzOpinion = pzOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.PZ_MAN
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.PZ_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getPzMan() {
        return pzMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.PZ_MAN
     *
     * @param pzMan the value for PROTECT.T_REMOTEINFOMANAGE.PZ_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setPzMan(String pzMan) {
        this.pzMan = pzMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.PZ_TIME
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.PZ_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public Date getPzTime() {
        return pzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.PZ_TIME
     *
     * @param pzTime the value for PROTECT.T_REMOTEINFOMANAGE.PZ_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setPzTime(Date pzTime) {
        this.pzTime = pzTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.XCZXJG
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.XCZXJG
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getXczxjg() {
        return xczxjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.XCZXJG
     *
     * @param xczxjg the value for PROTECT.T_REMOTEINFOMANAGE.XCZXJG
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setXczxjg(String xczxjg) {
        this.xczxjg = xczxjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.ZX_MAN
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.ZX_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getZxMan() {
        return zxMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.ZX_MAN
     *
     * @param zxMan the value for PROTECT.T_REMOTEINFOMANAGE.ZX_MAN
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setZxMan(String zxMan) {
        this.zxMan = zxMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.ZX_TIME
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.ZX_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public Date getZxTime() {
        return zxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.ZX_TIME
     *
     * @param zxTime the value for PROTECT.T_REMOTEINFOMANAGE.ZX_TIME
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setZxTime(Date zxTime) {
        this.zxTime = zxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.FJ
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.FJ
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getFj() {
        return fj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.FJ
     *
     * @param fj the value for PROTECT.T_REMOTEINFOMANAGE.FJ
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setFj(String fj) {
        this.fj = fj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.IS_JJD
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.IS_JJD
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getIsJjd() {
        return isJjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.IS_JJD
     *
     * @param isJjd the value for PROTECT.T_REMOTEINFOMANAGE.IS_JJD
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setIsJjd(String isJjd) {
        this.isJjd = isJjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.IS_PUT
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.IS_PUT
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getIsPut() {
        return isPut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.IS_PUT
     *
     * @param isPut the value for PROTECT.T_REMOTEINFOMANAGE.IS_PUT
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setIsPut(String isPut) {
        this.isPut = isPut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTECT.T_REMOTEINFOMANAGE.IS_ALLEDIT
     *
     * @return the value of PROTECT.T_REMOTEINFOMANAGE.IS_ALLEDIT
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getIsAlledit() {
        return isAlledit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTECT.T_REMOTEINFOMANAGE.IS_ALLEDIT
     *
     * @param isAlledit the value for PROTECT.T_REMOTEINFOMANAGE.IS_ALLEDIT
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setIsAlledit(String isAlledit) {
        this.isAlledit = isAlledit;
    }
}