package com.app.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TRemoteinfomanageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public TRemoteinfomanageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInfoIdIsNull() {
            addCriterion("INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNotNull() {
            addCriterion("INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIdEqualTo(String value) {
            addCriterion("INFO_ID =", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotEqualTo(String value) {
            addCriterion("INFO_ID <>", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThan(String value) {
            addCriterion("INFO_ID >", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_ID >=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThan(String value) {
            addCriterion("INFO_ID <", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThanOrEqualTo(String value) {
            addCriterion("INFO_ID <=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLike(String value) {
            addCriterion("INFO_ID like", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotLike(String value) {
            addCriterion("INFO_ID not like", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdIn(List<String> values) {
            addCriterion("INFO_ID in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotIn(List<String> values) {
            addCriterion("INFO_ID not in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdBetween(String value1, String value2) {
            addCriterion("INFO_ID between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotBetween(String value1, String value2) {
            addCriterion("INFO_ID not between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andJbxxIsNull() {
            addCriterion("JBXX is null");
            return (Criteria) this;
        }

        public Criteria andJbxxIsNotNull() {
            addCriterion("JBXX is not null");
            return (Criteria) this;
        }

        public Criteria andJbxxEqualTo(String value) {
            addCriterion("JBXX =", value, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxNotEqualTo(String value) {
            addCriterion("JBXX <>", value, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxGreaterThan(String value) {
            addCriterion("JBXX >", value, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxGreaterThanOrEqualTo(String value) {
            addCriterion("JBXX >=", value, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxLessThan(String value) {
            addCriterion("JBXX <", value, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxLessThanOrEqualTo(String value) {
            addCriterion("JBXX <=", value, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxLike(String value) {
            addCriterion("JBXX like", value, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxNotLike(String value) {
            addCriterion("JBXX not like", value, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxIn(List<String> values) {
            addCriterion("JBXX in", values, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxNotIn(List<String> values) {
            addCriterion("JBXX not in", values, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxBetween(String value1, String value2) {
            addCriterion("JBXX between", value1, value2, "jbxx");
            return (Criteria) this;
        }

        public Criteria andJbxxNotBetween(String value1, String value2) {
            addCriterion("JBXX not between", value1, value2, "jbxx");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("NUM is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("NUM is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("NUM =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("NUM <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("NUM >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("NUM >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("NUM <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("NUM <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("NUM like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("NUM not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("NUM in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("NUM not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("NUM between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("NUM not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andStationNameIsNull() {
            addCriterion("STATION_NAME is null");
            return (Criteria) this;
        }

        public Criteria andStationNameIsNotNull() {
            addCriterion("STATION_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andStationNameEqualTo(String value) {
            addCriterion("STATION_NAME =", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotEqualTo(String value) {
            addCriterion("STATION_NAME <>", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameGreaterThan(String value) {
            addCriterion("STATION_NAME >", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameGreaterThanOrEqualTo(String value) {
            addCriterion("STATION_NAME >=", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLessThan(String value) {
            addCriterion("STATION_NAME <", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLessThanOrEqualTo(String value) {
            addCriterion("STATION_NAME <=", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLike(String value) {
            addCriterion("STATION_NAME like", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotLike(String value) {
            addCriterion("STATION_NAME not like", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameIn(List<String> values) {
            addCriterion("STATION_NAME in", values, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotIn(List<String> values) {
            addCriterion("STATION_NAME not in", values, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameBetween(String value1, String value2) {
            addCriterion("STATION_NAME between", value1, value2, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotBetween(String value1, String value2) {
            addCriterion("STATION_NAME not between", value1, value2, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNull() {
            addCriterion("STATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("STATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStationIdEqualTo(String value) {
            addCriterion("STATION_ID =", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotEqualTo(String value) {
            addCriterion("STATION_ID <>", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThan(String value) {
            addCriterion("STATION_ID >", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(String value) {
            addCriterion("STATION_ID >=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThan(String value) {
            addCriterion("STATION_ID <", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThanOrEqualTo(String value) {
            addCriterion("STATION_ID <=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLike(String value) {
            addCriterion("STATION_ID like", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotLike(String value) {
            addCriterion("STATION_ID not like", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdIn(List<String> values) {
            addCriterion("STATION_ID in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotIn(List<String> values) {
            addCriterion("STATION_ID not in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdBetween(String value1, String value2) {
            addCriterion("STATION_ID between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotBetween(String value1, String value2) {
            addCriterion("STATION_ID not between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitIsNull() {
            addCriterion("DISPATCH_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitIsNotNull() {
            addCriterion("DISPATCH_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitEqualTo(String value) {
            addCriterion("DISPATCH_UNIT =", value, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitNotEqualTo(String value) {
            addCriterion("DISPATCH_UNIT <>", value, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitGreaterThan(String value) {
            addCriterion("DISPATCH_UNIT >", value, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitGreaterThanOrEqualTo(String value) {
            addCriterion("DISPATCH_UNIT >=", value, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitLessThan(String value) {
            addCriterion("DISPATCH_UNIT <", value, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitLessThanOrEqualTo(String value) {
            addCriterion("DISPATCH_UNIT <=", value, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitLike(String value) {
            addCriterion("DISPATCH_UNIT like", value, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitNotLike(String value) {
            addCriterion("DISPATCH_UNIT not like", value, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitIn(List<String> values) {
            addCriterion("DISPATCH_UNIT in", values, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitNotIn(List<String> values) {
            addCriterion("DISPATCH_UNIT not in", values, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitBetween(String value1, String value2) {
            addCriterion("DISPATCH_UNIT between", value1, value2, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitNotBetween(String value1, String value2) {
            addCriterion("DISPATCH_UNIT not between", value1, value2, "dispatchUnit");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidIsNull() {
            addCriterion("DISPATCH_UNITID is null");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidIsNotNull() {
            addCriterion("DISPATCH_UNITID is not null");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidEqualTo(String value) {
            addCriterion("DISPATCH_UNITID =", value, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidNotEqualTo(String value) {
            addCriterion("DISPATCH_UNITID <>", value, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidGreaterThan(String value) {
            addCriterion("DISPATCH_UNITID >", value, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidGreaterThanOrEqualTo(String value) {
            addCriterion("DISPATCH_UNITID >=", value, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidLessThan(String value) {
            addCriterion("DISPATCH_UNITID <", value, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidLessThanOrEqualTo(String value) {
            addCriterion("DISPATCH_UNITID <=", value, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidLike(String value) {
            addCriterion("DISPATCH_UNITID like", value, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidNotLike(String value) {
            addCriterion("DISPATCH_UNITID not like", value, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidIn(List<String> values) {
            addCriterion("DISPATCH_UNITID in", values, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidNotIn(List<String> values) {
            addCriterion("DISPATCH_UNITID not in", values, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidBetween(String value1, String value2) {
            addCriterion("DISPATCH_UNITID between", value1, value2, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andDispatchUnitidNotBetween(String value1, String value2) {
            addCriterion("DISPATCH_UNITID not between", value1, value2, "dispatchUnitid");
            return (Criteria) this;
        }

        public Criteria andZfbxhIsNull() {
            addCriterion("ZFBXH is null");
            return (Criteria) this;
        }

        public Criteria andZfbxhIsNotNull() {
            addCriterion("ZFBXH is not null");
            return (Criteria) this;
        }

        public Criteria andZfbxhEqualTo(String value) {
            addCriterion("ZFBXH =", value, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhNotEqualTo(String value) {
            addCriterion("ZFBXH <>", value, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhGreaterThan(String value) {
            addCriterion("ZFBXH >", value, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhGreaterThanOrEqualTo(String value) {
            addCriterion("ZFBXH >=", value, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhLessThan(String value) {
            addCriterion("ZFBXH <", value, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhLessThanOrEqualTo(String value) {
            addCriterion("ZFBXH <=", value, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhLike(String value) {
            addCriterion("ZFBXH like", value, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhNotLike(String value) {
            addCriterion("ZFBXH not like", value, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhIn(List<String> values) {
            addCriterion("ZFBXH in", values, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhNotIn(List<String> values) {
            addCriterion("ZFBXH not in", values, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhBetween(String value1, String value2) {
            addCriterion("ZFBXH between", value1, value2, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andZfbxhNotBetween(String value1, String value2) {
            addCriterion("ZFBXH not between", value1, value2, "zfbxh");
            return (Criteria) this;
        }

        public Criteria andIsZxIsNull() {
            addCriterion("IS_ZX is null");
            return (Criteria) this;
        }

        public Criteria andIsZxIsNotNull() {
            addCriterion("IS_ZX is not null");
            return (Criteria) this;
        }

        public Criteria andIsZxEqualTo(String value) {
            addCriterion("IS_ZX =", value, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxNotEqualTo(String value) {
            addCriterion("IS_ZX <>", value, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxGreaterThan(String value) {
            addCriterion("IS_ZX >", value, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxGreaterThanOrEqualTo(String value) {
            addCriterion("IS_ZX >=", value, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxLessThan(String value) {
            addCriterion("IS_ZX <", value, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxLessThanOrEqualTo(String value) {
            addCriterion("IS_ZX <=", value, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxLike(String value) {
            addCriterion("IS_ZX like", value, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxNotLike(String value) {
            addCriterion("IS_ZX not like", value, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxIn(List<String> values) {
            addCriterion("IS_ZX in", values, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxNotIn(List<String> values) {
            addCriterion("IS_ZX not in", values, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxBetween(String value1, String value2) {
            addCriterion("IS_ZX between", value1, value2, "isZx");
            return (Criteria) this;
        }

        public Criteria andIsZxNotBetween(String value1, String value2) {
            addCriterion("IS_ZX not between", value1, value2, "isZx");
            return (Criteria) this;
        }

        public Criteria andBzManIsNull() {
            addCriterion("BZ_MAN is null");
            return (Criteria) this;
        }

        public Criteria andBzManIsNotNull() {
            addCriterion("BZ_MAN is not null");
            return (Criteria) this;
        }

        public Criteria andBzManEqualTo(String value) {
            addCriterion("BZ_MAN =", value, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManNotEqualTo(String value) {
            addCriterion("BZ_MAN <>", value, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManGreaterThan(String value) {
            addCriterion("BZ_MAN >", value, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManGreaterThanOrEqualTo(String value) {
            addCriterion("BZ_MAN >=", value, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManLessThan(String value) {
            addCriterion("BZ_MAN <", value, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManLessThanOrEqualTo(String value) {
            addCriterion("BZ_MAN <=", value, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManLike(String value) {
            addCriterion("BZ_MAN like", value, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManNotLike(String value) {
            addCriterion("BZ_MAN not like", value, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManIn(List<String> values) {
            addCriterion("BZ_MAN in", values, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManNotIn(List<String> values) {
            addCriterion("BZ_MAN not in", values, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManBetween(String value1, String value2) {
            addCriterion("BZ_MAN between", value1, value2, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzManNotBetween(String value1, String value2) {
            addCriterion("BZ_MAN not between", value1, value2, "bzMan");
            return (Criteria) this;
        }

        public Criteria andBzTimeIsNull() {
            addCriterion("BZ_TIME is null");
            return (Criteria) this;
        }

        public Criteria andBzTimeIsNotNull() {
            addCriterion("BZ_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andBzTimeEqualTo(Date value) {
            addCriterion("BZ_TIME =", value, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzTimeNotEqualTo(Date value) {
            addCriterion("BZ_TIME <>", value, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzTimeGreaterThan(Date value) {
            addCriterion("BZ_TIME >", value, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("BZ_TIME >=", value, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzTimeLessThan(Date value) {
            addCriterion("BZ_TIME <", value, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzTimeLessThanOrEqualTo(Date value) {
            addCriterion("BZ_TIME <=", value, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzTimeIn(List<Date> values) {
            addCriterion("BZ_TIME in", values, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzTimeNotIn(List<Date> values) {
            addCriterion("BZ_TIME not in", values, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzTimeBetween(Date value1, Date value2) {
            addCriterion("BZ_TIME between", value1, value2, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzTimeNotBetween(Date value1, Date value2) {
            addCriterion("BZ_TIME not between", value1, value2, "bzTime");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneIsNull() {
            addCriterion("BZR_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneIsNotNull() {
            addCriterion("BZR_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneEqualTo(String value) {
            addCriterion("BZR_PHONE =", value, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneNotEqualTo(String value) {
            addCriterion("BZR_PHONE <>", value, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneGreaterThan(String value) {
            addCriterion("BZR_PHONE >", value, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("BZR_PHONE >=", value, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneLessThan(String value) {
            addCriterion("BZR_PHONE <", value, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneLessThanOrEqualTo(String value) {
            addCriterion("BZR_PHONE <=", value, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneLike(String value) {
            addCriterion("BZR_PHONE like", value, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneNotLike(String value) {
            addCriterion("BZR_PHONE not like", value, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneIn(List<String> values) {
            addCriterion("BZR_PHONE in", values, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneNotIn(List<String> values) {
            addCriterion("BZR_PHONE not in", values, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneBetween(String value1, String value2) {
            addCriterion("BZR_PHONE between", value1, value2, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andBzrPhoneNotBetween(String value1, String value2) {
            addCriterion("BZR_PHONE not between", value1, value2, "bzrPhone");
            return (Criteria) this;
        }

        public Criteria andRwmsIsNull() {
            addCriterion("RWMS is null");
            return (Criteria) this;
        }

        public Criteria andRwmsIsNotNull() {
            addCriterion("RWMS is not null");
            return (Criteria) this;
        }

        public Criteria andRwmsEqualTo(String value) {
            addCriterion("RWMS =", value, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsNotEqualTo(String value) {
            addCriterion("RWMS <>", value, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsGreaterThan(String value) {
            addCriterion("RWMS >", value, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsGreaterThanOrEqualTo(String value) {
            addCriterion("RWMS >=", value, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsLessThan(String value) {
            addCriterion("RWMS <", value, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsLessThanOrEqualTo(String value) {
            addCriterion("RWMS <=", value, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsLike(String value) {
            addCriterion("RWMS like", value, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsNotLike(String value) {
            addCriterion("RWMS not like", value, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsIn(List<String> values) {
            addCriterion("RWMS in", values, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsNotIn(List<String> values) {
            addCriterion("RWMS not in", values, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsBetween(String value1, String value2) {
            addCriterion("RWMS between", value1, value2, "rwms");
            return (Criteria) this;
        }

        public Criteria andRwmsNotBetween(String value1, String value2) {
            addCriterion("RWMS not between", value1, value2, "rwms");
            return (Criteria) this;
        }

        public Criteria andXcOpinionIsNull() {
            addCriterion("XC_OPINION is null");
            return (Criteria) this;
        }

        public Criteria andXcOpinionIsNotNull() {
            addCriterion("XC_OPINION is not null");
            return (Criteria) this;
        }

        public Criteria andXcOpinionEqualTo(String value) {
            addCriterion("XC_OPINION =", value, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionNotEqualTo(String value) {
            addCriterion("XC_OPINION <>", value, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionGreaterThan(String value) {
            addCriterion("XC_OPINION >", value, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("XC_OPINION >=", value, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionLessThan(String value) {
            addCriterion("XC_OPINION <", value, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionLessThanOrEqualTo(String value) {
            addCriterion("XC_OPINION <=", value, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionLike(String value) {
            addCriterion("XC_OPINION like", value, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionNotLike(String value) {
            addCriterion("XC_OPINION not like", value, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionIn(List<String> values) {
            addCriterion("XC_OPINION in", values, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionNotIn(List<String> values) {
            addCriterion("XC_OPINION not in", values, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionBetween(String value1, String value2) {
            addCriterion("XC_OPINION between", value1, value2, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andXcOpinionNotBetween(String value1, String value2) {
            addCriterion("XC_OPINION not between", value1, value2, "xcOpinion");
            return (Criteria) this;
        }

        public Criteria andJyManIsNull() {
            addCriterion("JY_MAN is null");
            return (Criteria) this;
        }

        public Criteria andJyManIsNotNull() {
            addCriterion("JY_MAN is not null");
            return (Criteria) this;
        }

        public Criteria andJyManEqualTo(String value) {
            addCriterion("JY_MAN =", value, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManNotEqualTo(String value) {
            addCriterion("JY_MAN <>", value, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManGreaterThan(String value) {
            addCriterion("JY_MAN >", value, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManGreaterThanOrEqualTo(String value) {
            addCriterion("JY_MAN >=", value, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManLessThan(String value) {
            addCriterion("JY_MAN <", value, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManLessThanOrEqualTo(String value) {
            addCriterion("JY_MAN <=", value, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManLike(String value) {
            addCriterion("JY_MAN like", value, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManNotLike(String value) {
            addCriterion("JY_MAN not like", value, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManIn(List<String> values) {
            addCriterion("JY_MAN in", values, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManNotIn(List<String> values) {
            addCriterion("JY_MAN not in", values, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManBetween(String value1, String value2) {
            addCriterion("JY_MAN between", value1, value2, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyManNotBetween(String value1, String value2) {
            addCriterion("JY_MAN not between", value1, value2, "jyMan");
            return (Criteria) this;
        }

        public Criteria andJyTimeIsNull() {
            addCriterion("JY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJyTimeIsNotNull() {
            addCriterion("JY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJyTimeEqualTo(Date value) {
            addCriterion("JY_TIME =", value, "jyTime");
            return (Criteria) this;
        }

        public Criteria andJyTimeNotEqualTo(Date value) {
            addCriterion("JY_TIME <>", value, "jyTime");
            return (Criteria) this;
        }

        public Criteria andJyTimeGreaterThan(Date value) {
            addCriterion("JY_TIME >", value, "jyTime");
            return (Criteria) this;
        }

        public Criteria andJyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("JY_TIME >=", value, "jyTime");
            return (Criteria) this;
        }

        public Criteria andJyTimeLessThan(Date value) {
            addCriterion("JY_TIME <", value, "jyTime");
            return (Criteria) this;
        }

        public Criteria andJyTimeLessThanOrEqualTo(Date value) {
            addCriterion("JY_TIME <=", value, "jyTime");
            return (Criteria) this;
        }

        public Criteria andJyTimeIn(List<Date> values) {
            addCriterion("JY_TIME in", values, "jyTime");
            return (Criteria) this;
        }

        public Criteria andJyTimeNotIn(List<Date> values) {
            addCriterion("JY_TIME not in", values, "jyTime");
            return (Criteria) this;
        }

        public Criteria andJyTimeBetween(Date value1, Date value2) {
            addCriterion("JY_TIME between", value1, value2, "jyTime");
            return (Criteria) this;
        }

        public Criteria andJyTimeNotBetween(Date value1, Date value2) {
            addCriterion("JY_TIME not between", value1, value2, "jyTime");
            return (Criteria) this;
        }

        public Criteria andShOpinionIsNull() {
            addCriterion("SH_OPINION is null");
            return (Criteria) this;
        }

        public Criteria andShOpinionIsNotNull() {
            addCriterion("SH_OPINION is not null");
            return (Criteria) this;
        }

        public Criteria andShOpinionEqualTo(String value) {
            addCriterion("SH_OPINION =", value, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionNotEqualTo(String value) {
            addCriterion("SH_OPINION <>", value, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionGreaterThan(String value) {
            addCriterion("SH_OPINION >", value, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("SH_OPINION >=", value, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionLessThan(String value) {
            addCriterion("SH_OPINION <", value, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionLessThanOrEqualTo(String value) {
            addCriterion("SH_OPINION <=", value, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionLike(String value) {
            addCriterion("SH_OPINION like", value, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionNotLike(String value) {
            addCriterion("SH_OPINION not like", value, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionIn(List<String> values) {
            addCriterion("SH_OPINION in", values, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionNotIn(List<String> values) {
            addCriterion("SH_OPINION not in", values, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionBetween(String value1, String value2) {
            addCriterion("SH_OPINION between", value1, value2, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShOpinionNotBetween(String value1, String value2) {
            addCriterion("SH_OPINION not between", value1, value2, "shOpinion");
            return (Criteria) this;
        }

        public Criteria andShManIsNull() {
            addCriterion("SH_MAN is null");
            return (Criteria) this;
        }

        public Criteria andShManIsNotNull() {
            addCriterion("SH_MAN is not null");
            return (Criteria) this;
        }

        public Criteria andShManEqualTo(String value) {
            addCriterion("SH_MAN =", value, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManNotEqualTo(String value) {
            addCriterion("SH_MAN <>", value, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManGreaterThan(String value) {
            addCriterion("SH_MAN >", value, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManGreaterThanOrEqualTo(String value) {
            addCriterion("SH_MAN >=", value, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManLessThan(String value) {
            addCriterion("SH_MAN <", value, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManLessThanOrEqualTo(String value) {
            addCriterion("SH_MAN <=", value, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManLike(String value) {
            addCriterion("SH_MAN like", value, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManNotLike(String value) {
            addCriterion("SH_MAN not like", value, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManIn(List<String> values) {
            addCriterion("SH_MAN in", values, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManNotIn(List<String> values) {
            addCriterion("SH_MAN not in", values, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManBetween(String value1, String value2) {
            addCriterion("SH_MAN between", value1, value2, "shMan");
            return (Criteria) this;
        }

        public Criteria andShManNotBetween(String value1, String value2) {
            addCriterion("SH_MAN not between", value1, value2, "shMan");
            return (Criteria) this;
        }

        public Criteria andShTimeIsNull() {
            addCriterion("SH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andShTimeIsNotNull() {
            addCriterion("SH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andShTimeEqualTo(Date value) {
            addCriterion("SH_TIME =", value, "shTime");
            return (Criteria) this;
        }

        public Criteria andShTimeNotEqualTo(Date value) {
            addCriterion("SH_TIME <>", value, "shTime");
            return (Criteria) this;
        }

        public Criteria andShTimeGreaterThan(Date value) {
            addCriterion("SH_TIME >", value, "shTime");
            return (Criteria) this;
        }

        public Criteria andShTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SH_TIME >=", value, "shTime");
            return (Criteria) this;
        }

        public Criteria andShTimeLessThan(Date value) {
            addCriterion("SH_TIME <", value, "shTime");
            return (Criteria) this;
        }

        public Criteria andShTimeLessThanOrEqualTo(Date value) {
            addCriterion("SH_TIME <=", value, "shTime");
            return (Criteria) this;
        }

        public Criteria andShTimeIn(List<Date> values) {
            addCriterion("SH_TIME in", values, "shTime");
            return (Criteria) this;
        }

        public Criteria andShTimeNotIn(List<Date> values) {
            addCriterion("SH_TIME not in", values, "shTime");
            return (Criteria) this;
        }

        public Criteria andShTimeBetween(Date value1, Date value2) {
            addCriterion("SH_TIME between", value1, value2, "shTime");
            return (Criteria) this;
        }

        public Criteria andShTimeNotBetween(Date value1, Date value2) {
            addCriterion("SH_TIME not between", value1, value2, "shTime");
            return (Criteria) this;
        }

        public Criteria andPzOpinionIsNull() {
            addCriterion("PZ_OPINION is null");
            return (Criteria) this;
        }

        public Criteria andPzOpinionIsNotNull() {
            addCriterion("PZ_OPINION is not null");
            return (Criteria) this;
        }

        public Criteria andPzOpinionEqualTo(String value) {
            addCriterion("PZ_OPINION =", value, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionNotEqualTo(String value) {
            addCriterion("PZ_OPINION <>", value, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionGreaterThan(String value) {
            addCriterion("PZ_OPINION >", value, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("PZ_OPINION >=", value, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionLessThan(String value) {
            addCriterion("PZ_OPINION <", value, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionLessThanOrEqualTo(String value) {
            addCriterion("PZ_OPINION <=", value, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionLike(String value) {
            addCriterion("PZ_OPINION like", value, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionNotLike(String value) {
            addCriterion("PZ_OPINION not like", value, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionIn(List<String> values) {
            addCriterion("PZ_OPINION in", values, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionNotIn(List<String> values) {
            addCriterion("PZ_OPINION not in", values, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionBetween(String value1, String value2) {
            addCriterion("PZ_OPINION between", value1, value2, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzOpinionNotBetween(String value1, String value2) {
            addCriterion("PZ_OPINION not between", value1, value2, "pzOpinion");
            return (Criteria) this;
        }

        public Criteria andPzManIsNull() {
            addCriterion("PZ_MAN is null");
            return (Criteria) this;
        }

        public Criteria andPzManIsNotNull() {
            addCriterion("PZ_MAN is not null");
            return (Criteria) this;
        }

        public Criteria andPzManEqualTo(String value) {
            addCriterion("PZ_MAN =", value, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManNotEqualTo(String value) {
            addCriterion("PZ_MAN <>", value, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManGreaterThan(String value) {
            addCriterion("PZ_MAN >", value, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManGreaterThanOrEqualTo(String value) {
            addCriterion("PZ_MAN >=", value, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManLessThan(String value) {
            addCriterion("PZ_MAN <", value, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManLessThanOrEqualTo(String value) {
            addCriterion("PZ_MAN <=", value, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManLike(String value) {
            addCriterion("PZ_MAN like", value, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManNotLike(String value) {
            addCriterion("PZ_MAN not like", value, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManIn(List<String> values) {
            addCriterion("PZ_MAN in", values, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManNotIn(List<String> values) {
            addCriterion("PZ_MAN not in", values, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManBetween(String value1, String value2) {
            addCriterion("PZ_MAN between", value1, value2, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzManNotBetween(String value1, String value2) {
            addCriterion("PZ_MAN not between", value1, value2, "pzMan");
            return (Criteria) this;
        }

        public Criteria andPzTimeIsNull() {
            addCriterion("PZ_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPzTimeIsNotNull() {
            addCriterion("PZ_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPzTimeEqualTo(Date value) {
            addCriterion("PZ_TIME =", value, "pzTime");
            return (Criteria) this;
        }

        public Criteria andPzTimeNotEqualTo(Date value) {
            addCriterion("PZ_TIME <>", value, "pzTime");
            return (Criteria) this;
        }

        public Criteria andPzTimeGreaterThan(Date value) {
            addCriterion("PZ_TIME >", value, "pzTime");
            return (Criteria) this;
        }

        public Criteria andPzTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PZ_TIME >=", value, "pzTime");
            return (Criteria) this;
        }

        public Criteria andPzTimeLessThan(Date value) {
            addCriterion("PZ_TIME <", value, "pzTime");
            return (Criteria) this;
        }

        public Criteria andPzTimeLessThanOrEqualTo(Date value) {
            addCriterion("PZ_TIME <=", value, "pzTime");
            return (Criteria) this;
        }

        public Criteria andPzTimeIn(List<Date> values) {
            addCriterion("PZ_TIME in", values, "pzTime");
            return (Criteria) this;
        }

        public Criteria andPzTimeNotIn(List<Date> values) {
            addCriterion("PZ_TIME not in", values, "pzTime");
            return (Criteria) this;
        }

        public Criteria andPzTimeBetween(Date value1, Date value2) {
            addCriterion("PZ_TIME between", value1, value2, "pzTime");
            return (Criteria) this;
        }

        public Criteria andPzTimeNotBetween(Date value1, Date value2) {
            addCriterion("PZ_TIME not between", value1, value2, "pzTime");
            return (Criteria) this;
        }

        public Criteria andXczxjgIsNull() {
            addCriterion("XCZXJG is null");
            return (Criteria) this;
        }

        public Criteria andXczxjgIsNotNull() {
            addCriterion("XCZXJG is not null");
            return (Criteria) this;
        }

        public Criteria andXczxjgEqualTo(String value) {
            addCriterion("XCZXJG =", value, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgNotEqualTo(String value) {
            addCriterion("XCZXJG <>", value, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgGreaterThan(String value) {
            addCriterion("XCZXJG >", value, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgGreaterThanOrEqualTo(String value) {
            addCriterion("XCZXJG >=", value, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgLessThan(String value) {
            addCriterion("XCZXJG <", value, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgLessThanOrEqualTo(String value) {
            addCriterion("XCZXJG <=", value, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgLike(String value) {
            addCriterion("XCZXJG like", value, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgNotLike(String value) {
            addCriterion("XCZXJG not like", value, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgIn(List<String> values) {
            addCriterion("XCZXJG in", values, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgNotIn(List<String> values) {
            addCriterion("XCZXJG not in", values, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgBetween(String value1, String value2) {
            addCriterion("XCZXJG between", value1, value2, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andXczxjgNotBetween(String value1, String value2) {
            addCriterion("XCZXJG not between", value1, value2, "xczxjg");
            return (Criteria) this;
        }

        public Criteria andZxManIsNull() {
            addCriterion("ZX_MAN is null");
            return (Criteria) this;
        }

        public Criteria andZxManIsNotNull() {
            addCriterion("ZX_MAN is not null");
            return (Criteria) this;
        }

        public Criteria andZxManEqualTo(String value) {
            addCriterion("ZX_MAN =", value, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManNotEqualTo(String value) {
            addCriterion("ZX_MAN <>", value, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManGreaterThan(String value) {
            addCriterion("ZX_MAN >", value, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManGreaterThanOrEqualTo(String value) {
            addCriterion("ZX_MAN >=", value, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManLessThan(String value) {
            addCriterion("ZX_MAN <", value, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManLessThanOrEqualTo(String value) {
            addCriterion("ZX_MAN <=", value, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManLike(String value) {
            addCriterion("ZX_MAN like", value, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManNotLike(String value) {
            addCriterion("ZX_MAN not like", value, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManIn(List<String> values) {
            addCriterion("ZX_MAN in", values, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManNotIn(List<String> values) {
            addCriterion("ZX_MAN not in", values, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManBetween(String value1, String value2) {
            addCriterion("ZX_MAN between", value1, value2, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxManNotBetween(String value1, String value2) {
            addCriterion("ZX_MAN not between", value1, value2, "zxMan");
            return (Criteria) this;
        }

        public Criteria andZxTimeIsNull() {
            addCriterion("ZX_TIME is null");
            return (Criteria) this;
        }

        public Criteria andZxTimeIsNotNull() {
            addCriterion("ZX_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andZxTimeEqualTo(Date value) {
            addCriterion("ZX_TIME =", value, "zxTime");
            return (Criteria) this;
        }

        public Criteria andZxTimeNotEqualTo(Date value) {
            addCriterion("ZX_TIME <>", value, "zxTime");
            return (Criteria) this;
        }

        public Criteria andZxTimeGreaterThan(Date value) {
            addCriterion("ZX_TIME >", value, "zxTime");
            return (Criteria) this;
        }

        public Criteria andZxTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ZX_TIME >=", value, "zxTime");
            return (Criteria) this;
        }

        public Criteria andZxTimeLessThan(Date value) {
            addCriterion("ZX_TIME <", value, "zxTime");
            return (Criteria) this;
        }

        public Criteria andZxTimeLessThanOrEqualTo(Date value) {
            addCriterion("ZX_TIME <=", value, "zxTime");
            return (Criteria) this;
        }

        public Criteria andZxTimeIn(List<Date> values) {
            addCriterion("ZX_TIME in", values, "zxTime");
            return (Criteria) this;
        }

        public Criteria andZxTimeNotIn(List<Date> values) {
            addCriterion("ZX_TIME not in", values, "zxTime");
            return (Criteria) this;
        }

        public Criteria andZxTimeBetween(Date value1, Date value2) {
            addCriterion("ZX_TIME between", value1, value2, "zxTime");
            return (Criteria) this;
        }

        public Criteria andZxTimeNotBetween(Date value1, Date value2) {
            addCriterion("ZX_TIME not between", value1, value2, "zxTime");
            return (Criteria) this;
        }

        public Criteria andFjIsNull() {
            addCriterion("FJ is null");
            return (Criteria) this;
        }

        public Criteria andFjIsNotNull() {
            addCriterion("FJ is not null");
            return (Criteria) this;
        }

        public Criteria andFjEqualTo(String value) {
            addCriterion("FJ =", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjNotEqualTo(String value) {
            addCriterion("FJ <>", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjGreaterThan(String value) {
            addCriterion("FJ >", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjGreaterThanOrEqualTo(String value) {
            addCriterion("FJ >=", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjLessThan(String value) {
            addCriterion("FJ <", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjLessThanOrEqualTo(String value) {
            addCriterion("FJ <=", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjLike(String value) {
            addCriterion("FJ like", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjNotLike(String value) {
            addCriterion("FJ not like", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjIn(List<String> values) {
            addCriterion("FJ in", values, "fj");
            return (Criteria) this;
        }

        public Criteria andFjNotIn(List<String> values) {
            addCriterion("FJ not in", values, "fj");
            return (Criteria) this;
        }

        public Criteria andFjBetween(String value1, String value2) {
            addCriterion("FJ between", value1, value2, "fj");
            return (Criteria) this;
        }

        public Criteria andFjNotBetween(String value1, String value2) {
            addCriterion("FJ not between", value1, value2, "fj");
            return (Criteria) this;
        }

        public Criteria andIsJjdIsNull() {
            addCriterion("IS_JJD is null");
            return (Criteria) this;
        }

        public Criteria andIsJjdIsNotNull() {
            addCriterion("IS_JJD is not null");
            return (Criteria) this;
        }

        public Criteria andIsJjdEqualTo(String value) {
            addCriterion("IS_JJD =", value, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdNotEqualTo(String value) {
            addCriterion("IS_JJD <>", value, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdGreaterThan(String value) {
            addCriterion("IS_JJD >", value, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdGreaterThanOrEqualTo(String value) {
            addCriterion("IS_JJD >=", value, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdLessThan(String value) {
            addCriterion("IS_JJD <", value, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdLessThanOrEqualTo(String value) {
            addCriterion("IS_JJD <=", value, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdLike(String value) {
            addCriterion("IS_JJD like", value, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdNotLike(String value) {
            addCriterion("IS_JJD not like", value, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdIn(List<String> values) {
            addCriterion("IS_JJD in", values, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdNotIn(List<String> values) {
            addCriterion("IS_JJD not in", values, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdBetween(String value1, String value2) {
            addCriterion("IS_JJD between", value1, value2, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsJjdNotBetween(String value1, String value2) {
            addCriterion("IS_JJD not between", value1, value2, "isJjd");
            return (Criteria) this;
        }

        public Criteria andIsPutIsNull() {
            addCriterion("IS_PUT is null");
            return (Criteria) this;
        }

        public Criteria andIsPutIsNotNull() {
            addCriterion("IS_PUT is not null");
            return (Criteria) this;
        }

        public Criteria andIsPutEqualTo(String value) {
            addCriterion("IS_PUT =", value, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutNotEqualTo(String value) {
            addCriterion("IS_PUT <>", value, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutGreaterThan(String value) {
            addCriterion("IS_PUT >", value, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutGreaterThanOrEqualTo(String value) {
            addCriterion("IS_PUT >=", value, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutLessThan(String value) {
            addCriterion("IS_PUT <", value, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutLessThanOrEqualTo(String value) {
            addCriterion("IS_PUT <=", value, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutLike(String value) {
            addCriterion("IS_PUT like", value, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutNotLike(String value) {
            addCriterion("IS_PUT not like", value, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutIn(List<String> values) {
            addCriterion("IS_PUT in", values, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutNotIn(List<String> values) {
            addCriterion("IS_PUT not in", values, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutBetween(String value1, String value2) {
            addCriterion("IS_PUT between", value1, value2, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsPutNotBetween(String value1, String value2) {
            addCriterion("IS_PUT not between", value1, value2, "isPut");
            return (Criteria) this;
        }

        public Criteria andIsAlleditIsNull() {
            addCriterion("IS_ALLEDIT is null");
            return (Criteria) this;
        }

        public Criteria andIsAlleditIsNotNull() {
            addCriterion("IS_ALLEDIT is not null");
            return (Criteria) this;
        }

        public Criteria andIsAlleditEqualTo(String value) {
            addCriterion("IS_ALLEDIT =", value, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditNotEqualTo(String value) {
            addCriterion("IS_ALLEDIT <>", value, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditGreaterThan(String value) {
            addCriterion("IS_ALLEDIT >", value, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditGreaterThanOrEqualTo(String value) {
            addCriterion("IS_ALLEDIT >=", value, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditLessThan(String value) {
            addCriterion("IS_ALLEDIT <", value, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditLessThanOrEqualTo(String value) {
            addCriterion("IS_ALLEDIT <=", value, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditLike(String value) {
            addCriterion("IS_ALLEDIT like", value, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditNotLike(String value) {
            addCriterion("IS_ALLEDIT not like", value, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditIn(List<String> values) {
            addCriterion("IS_ALLEDIT in", values, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditNotIn(List<String> values) {
            addCriterion("IS_ALLEDIT not in", values, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditBetween(String value1, String value2) {
            addCriterion("IS_ALLEDIT between", value1, value2, "isAlledit");
            return (Criteria) this;
        }

        public Criteria andIsAlleditNotBetween(String value1, String value2) {
            addCriterion("IS_ALLEDIT not between", value1, value2, "isAlledit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 27 11:19:42 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROTECT.T_REMOTEINFOMANAGE
     *
     * @mbg.generated Sat Oct 27 11:19:42 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}